'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SuperMarketTestEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SuperMarketTestEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Customers() As DbSet(Of Customer)
    Public Overridable Property CustomerOrders() As DbSet(Of CustomerOrder)
    Public Overridable Property Markets() As DbSet(Of Market)
    Public Overridable Property OrderItems() As DbSet(Of OrderItem)
    Public Overridable Property Products() As DbSet(Of Product)
    Public Overridable Property Stocks() As DbSet(Of Stock)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Warehouses() As DbSet(Of Warehouse)

End Class
