'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductID As Integer
    Public Property Name As String
    Public Property Brand As String
    Public Property Price As Decimal

    Public Overridable Property OrderItems As ICollection(Of OrderItem) = New HashSet(Of OrderItem)
    Public Overridable Property Stocks As ICollection(Of Stock) = New HashSet(Of Stock)

End Class
